### ISSUE TITLE
exceptions episode

### ISSUE THREAD

**Issue by DC23** [csiro-data-school/python#10]
Episode 07 requires lecture notes and exercises.

**Comment by DC23** [comment]
I might have time this afternoon to work on this, after I get to Melbourne. Will check in then to see

**Comment by KerensaMcElroy** [comment]
?thanks Daniel,


we've done some good work this morning and I'll keep going...

________________________________

**Comment by DC23** [comment]
picking this up now, I thought of some ideas on the plane. I will include a comparison between look before you leap vs easier to ask forgiveness than permission (aka the Pythonic way that relies on exceptions).

I will also try to use cloze exercises. They are a good fit for the format, I should have used more in previous episodes.

**Comment by DC23** [comment]
first version is complete. Moving into python-adv repo
