### ISSUE TITLE
Understanding errors content

### ISSUE THREAD

**Issue by KerensaMcElroy** [csiro-data-school/python#62]
Content can be found here: 

https://csiro-data-school.github.io/python/11-errors/index.html (already in the introductory lesson)

and: 

https://csiro-data-school.github.io/python-adv/03-documentation/index.html

and here:

https://csiro-data-school.github.io/python-adv/05-exceptions/index.html (the handling of errors, and raising exceptions content in this episode is out of scope for a beginner course)

**Comment by jaredraynes** [comment]
Have merged errors and exceptions from python-adv to python (introduction). Have not included the documentation part yet
