### ISSUE TITLE
Reading from files content

### ISSUE THREAD

**Issue by KerensaMcElroy** [csiro-data-school/python#63]
Content can be found here:

https://csiro-data-school.github.io/python-files/10-files/index.html (from memory, this lesson worked really well)

and here:

https://csiro-data-school.github.io/python-adv/10-files/index.html

NOTE: I would strongly recommend taking the first approach, and not going into details about opening / closing files and context managers, instead just introducing the file opening recipe, and not providing any alternatives

**Comment by KerensaMcElroy** [comment]
This episode is cool in that it shows how to work with the lines of content in a file. If used, might need to be substantially modified for this context though:

https://csiro-data-school.github.io/python-files/11-processing/index.html

The files episode also has to come after loops.

**Comment by jaredraynes** [comment]
Have added to repo
